### ISSUE TITLE
ssl not installing, this warning appears

### ISSUE THREAD

**Issue by SharisrSisir** [pypa/ssl#9]
ERROR: Command errored out with exit status 1:
     command: /home/spider/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h1w4448c/ssl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h1w4448c/ssl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-h1w4448c/ssl/pip-egg-info
         cwd: /tmp/pip-install-h1w4448c/ssl/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h1w4448c/ssl/setup.py", line 33
        print 'looking for', f
                          ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('looking for', f)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by di** [comment]
Hi @SharisrSisir, this issue tracker is for the codebase behind `pypi.org`, not the projects hosted on it.

It looks like you're trying to `pip install ssl` with Python 3, but this project is only designed for Python 2. You don't need to `pip install ssl` in Python 3 because [it is already in the standard library](https://docs.python.org/3/library/ssl.html), meaning it is already available for you to `import ssl`.
